spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jdbc:
        time_zone: UTC
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
        provider:
          okta:
            authorization-uri: ${OKTA_AUTHORIZATION_URI}
            token-uri: ${OKTA_TOKEN_URI}
            user-info-uri: ${OKTA_USER_INFO_URI}
            user-name-attribute: sub
            jwk-set-uri: ${OKTA_JWK_SET_URI}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: TRACE
    org.apache.coyote.http11.Http11Processor: TRACE
    org.apache.tomcat.util.net.NioEndpoint: TRACE
    org.apache.catalina.connector: TRACE
    root: DEBUG

server:
  tomcat:
    max-http-header-size: 8192
