spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:

      jdbc:
        time_zone: UTC
    show-sql: false # Set true for debugging
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: always

