spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jdbc:
        time_zone: UTC
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: always
okta:
  oauth2:
    issuer: https://dev-50314961.okta.com/oauth2/default
    client-id: 0oai07jex0g6NGTZx5d7
    redirect-uri: http://localhost:8080/login/callback
    client-secret: r8nR4zxnXy8tisYRqM6km-4-26Ub2cI_T5N9I1iVA-UNZCaEiA3CWOz_1GPS191H


logging:
  level:
    root: debug



