spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jdbc:
        time_zone: UTC
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: "http://localhost:5173, https://fitnessplaner-frontend-webtech-ss24-e6t9.onrender.com"
      allowed-methods: "*"
      allowed-headers: "*"
  sql:
    init:
      platform: postgres
      mode: always
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oahnnohukLTsAD3h5d7
            scope: openid, profile, email
            redirect-uri: "http://localhost:5173/login/callback, https://fitnessplaner-frontend-webtech-ss24-e6t9.onrender.com/login/callback"
            authorization-grant-type: authorization_code
            client-authentication-method: post
      provider:
        okta:
          issuer-uri: https://dev-50314961.okta.com/oauth2/default
okta:
  oauth2:
    issuer: https://dev-50314961.okta.com/oauth2/default
    client-id: 0oahnnohukLTsAD3h5d7
