spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jdbc:
        time_zone: UTC
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: always

okta:
  oauth2:
    issuer: https://dev-50314961.okta.com/oauth2/default
    client-id: oahnnohukLTsAD3h5d7
    redirect-uri: http://localhost:8080/login/callback
