name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 21

      - name: Grant execute permission for Gradle wrapper (if necessary)
        run: chmod +x ./gradlew

      - name: Clean build and run tests
        run: ./gradlew clean test --info --stacktrace
